INSERT INTO
    breeds (breed_name)
VALUES
    ('Affenpinscher'),
    ('Afghan Hound'),
    ('Airedale Terrier'),
    ('Akita'),
    ('Alaskan Klee Kai'),
    ('Alaskan Malamute'),
    ('American Bulldog'),
    ('American English Coonhound'),
    ('American Eskimo Dog'),
    ('American Foxhound'),
    ('American Hairless Terrier'),
    ('American Leopard Hound'),
    ('American Pit Bull Terrier'),
    ('American Staffordshire Terrier'),
    ('American Water Spaniel'),
    ('Anatolian Shepherd Dog'),
    ('Appenzeller Sennenhund'),
    ('Aussiedoodle'),
    ('Australian Cattle Dog'),
    ('Australian Kelpie'),
    ('Australian Shepherd'),
    ('Australian Stumpy Tail Cattle Dog'),
    ('Australian Terrier'),
    ('Azawakh'),
    ('Barbet'),
    ('Basenji'),
    ('Basset Fauve de Bretagne'),
    ('Basset Hound'),
    ('Bavarian Mountain Scent Hound'),
    ('Beagle'),
    ('Bearded Collie'),
    ('Beauceron'),
    ('Bedlington Terrier'),
    ('Belgian Laekenois'),
    ('Belgian Malinois'),
    ('Belgian Sheepdog'),
    ('Belgian Tervuren'),
    ('Bergamasco Sheepdog'),
    ('Berger Picard'),
    ('Bernese Mountain Dog'),
    ('Bichon Frise'),
    ('Biewer Terrier'),
    ('Black and Tan Coonhound'),
    ('Black Russian Terrier'),
    ('Bloodhound'),
    ('Bluetick Coonhound'),
    ('Boerboel'),
    ('Bolognese'),
    ('Border Collie'),
    ('Border Terrier'),
    ('Borzoi'),
    ('Boston Terrier'),
    ('Bouvier des Flandres'),
    ('Boxer'),
    ('Boykin Spaniel'),
    ('Bracco Italiano'),
    ('Braque du Bourbonnais'),
    ('Braque Francais'),
    ('Briard'),
    ('Brittany'),
    ('Brussels Griffon'),
    ('Bull Terrier'),
    ('Bulldog'),
    ('Bullmastiff'),
    ('Cairn Terrier'),
    ('Canaan Dog'),
    ('Cane Corso'),
    ('Cardigan Welsh Corgi'),
    ('Carolina Dog'),
    ('Catahoula Leopard Dog'),
    ('Caucasian Shepherd Dog'),
    ('Cavalier King Charles Spaniel'),
    ('Central Asian Shepherd Dog'),
    ('Cesky Terrier'),
    ('Chesapeake Bay Retriever'),
    ('Chihuahua'),
    ('Chinese Crested'),
    ('Chinese Shar-Pei'),
    ('Chinook'),
    ('Chow Chow'),
    ('Cirneco dell’Etna'),
    ('Clumber Spaniel'),
    ('Cocker Spaniel'),
    ('Collie'),
    ('Coton de Tulear'),
    ('Curly-Coated Retriever'),
    ('Dachshund'),
    ('Dalmatian'),
    ('Dandie Dinmont Terrier'),
    ('Doberman Pinscher'),
    ('Dogo Argentino'),
    ('Dogue de Bordeaux'),
    ('Drentsche Patrijshond'),
    ('Drever'),
    ('Dutch Shepherd'),
    ('English Cocker Spaniel'),
    ('English Foxhound'),
    ('English Setter'),
    ('English Springer Spaniel'),
    ('English Toy Spaniel'),
    ('Entlebucher Mountain Dog'),
    ('Estrela Mountain Dog'),
    ('Eurasier'),
    ('Field Spaniel'),
    ('Finnish Lapphund'),
    ('Finnish Spitz'),
    ('Flat-Coated Retriever'),
    ('French Bulldog'),
    ('German Longhaired Pointer'),
    ('German Pinscher'),
    ('German Shepherd Dog'),
    ('German Shorthaired Pointer'),
    ('German Spitz'),
    ('German Wirehaired Pointer'),
    ('Giant Schnauzer'),
    ('Glen of Imaal Terrier'),
    ('Golden Retriever'),
    ('Gordon Setter'),
    ('Great Dane'),
    ('Great Pyrenees'),
    ('Greater Swiss Mountain Dog'),
    ('Greyhound'),
    ('Hamiltonstovare'),
    ('Harrier'),
    ('Havanese'),
    ('Hokkaido'),
    ('Hovawart'),
    ('Ibizan Hound'),
    ('Icelandic Sheepdog'),
    ('Irish Red and White Setter'),
    ('Irish Setter'),
    ('Irish Terrier'),
    ('Irish Water Spaniel'),
    ('Irish Wolfhound'),
    ('Italian Greyhound'),
    ('Italian Spinone'),
    ('Jack Russell Terrier'),
    ('Japanese Akitainu'),
    ('Japanese Chin'),
    ('Japanese Spitz'),
    ('Japanese Terrier'),
    ('Kangal Shepherd Dog'),
    ('Keeshond'),
    ('Kerry Blue Terrier'),
    ('King Shepherd'),
    ('Komondor'),
    ('Kooikerhondje'),
    ('Korean Jindo'),
    ('Kuvasz'),
    ('Labrador Retriever'),
    ('Lagotto Romagnolo'),
    ('Lakeland Terrier'),
    ('Lancashire Heeler'),
    ('Leonberger'),
    ('Lhasa Apso'),
    ('Lowchen'),
    ('Maltese'),
    ('Manchester Terrier'),
    ('Maremma Sheepdog'),
    ('Mastiff'),
    ('Miniature American Shepherd'),
    ('Miniature Bull Terrier'),
    ('Miniature Pinscher'),
    ('Miniature Schnauzer'),
    ('Mountain Cur'),
    ('Mudi'),
    ('Neapolitan Mastiff'),
    ('Newfoundland'),
    ('Norfolk Terrier'),
    ('Norrbottenspets'),
    ('Norwegian Buhund'),
    ('Norwegian Elkhound'),
    ('Norwegian Lundehund'),
    ('Norwich Terrier'),
    ('Nova Scotia Duck Tolling Retriever'),
    ('Old English Sheepdog'),
    ('Otterhound'),
    ('Papillon'),
    ('Parson Russell Terrier'),
    ('Patterdale Terrier'),
    ('Pekingese'),
    ('Pembroke Welsh Corgi'),
    ('Perro de Presa Canario'),
    ('Peruvian Inca Orchid'),
    ('Petit Basset Griffon Vendéen'),
    ('Pharaoh Hound'),
    ('Plott Hound'),
    ('Pointer'),
    ('Polish Lowland Sheepdog'),
    ('Pomeranian'),
    ('Poodle'),
    ('Portuguese Podengo'),
    ('Portuguese Podengo Pequeno'),
    ('Portuguese Pointer'),
    ('Portuguese Sheepdog'),
    ('Portuguese Water Dog'),
    ('Presa Canario'),
    ('Pug'),
    ('Puli'),
    ('Pumi'),
    ('Pyrenean Mastiff'),
    ('Pyrenean Shepherd'),
    ('Rat Terrier'),
    ('Redbone Coonhound'),
    ('Rhodesian Ridgeback'),
    ('Rottweiler'),
    ('Russell Terrier'),
    ('Russian Toy'),
    ('Saint Bernard'),
    ('Saluki'),
    ('Samoyed'),
    ('Schipperke'),
    ('Scottish Deerhound'),
    ('Scottish Terrier'),
    ('Sealyham Terrier'),
    ('Segugio Italiano'),
    ('Shetland Sheepdog'),
    ('Shiba Inu'),
    ('Shih Tzu'),
    ('Shikoku'),
    ('Siberian Husky'),
    ('Silky Terrier'),
    ('Skye Terrier'),
    ('Sloughi'),
    ('Small Munsterlander'),
    ('Smooth Fox Terrier'),
    ('Soft Coated Wheaten Terrier'),
    ('Spanish Mastiff'),
    ('Spanish Water Dog'),
    ('Spinone Italiano'),
    ('Staffordshire Bull Terrier'),
    ('Standard Schnauzer'),
    ('Sussex Spaniel'),
    ('Swedish Lapphund'),
    ('Swedish Vallhund'),
    ('Taiwan Dog'),
    ('Teddy Roosevelt Terrier'),
    ('Thai Ridgeback'),
    ('Tibetan Mastiff'),
    ('Tibetan Spaniel'),
    ('Tibetan Terrier'),
    ('Tosa'),
    ('Toy Fox Terrier'),
    ('Treeing Tennessee Brindle'),
    ('Treeing Walker Coonhound'),
    ('Vizsla'),
    ('Weimaraner'),
    ('Welsh Springer Spaniel'),
    ('Welsh Terrier'),
    ('West Highland White Terrier'),
    ('Whippet'),
    ('Wire Fox Terrier'),
    ('Wirehaired Pointing Griffon'),
    ('Wirehaired Vizsla'),
    ('Xoloitzcuintli'),
    ('Yorkshire Terrier');